"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {onAuthStateChanged} from "firebase/auth";
import {learnerAuth} from "../../lib/firebase";
import {learnerFunction} from "../../lib/learner-api";
import LearnerNav from "../components/LearnerNav";
type Reward={id:string;name:string;type:string;description:string;coinCost:number};type Data={wallet:{balance:number;earned:number;spent:number};rewards:Reward[];redemptions:any[]};
export default function Rewards(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState("");
useEffect(()=>onAuthStateChanged(learnerAuth,async u=>{if(!u)return;try{setData(await learnerFunction("getLearnerRewards",{},await u.getIdToken()));}catch(e:any){setError(e.message);}}),[]);
async function redeem(id:string){if(!learnerAuth.currentUser)return;setBusy(id);try{await learnerFunction("redeemReward",{rewardId:id},await learnerAuth.currentUser.getIdToken());setData(await learnerFunction("getLearnerRewards",{},await learnerAuth.currentUser.getIdToken()));}catch(e:any){setError(e.message);}finally{setBusy("");}}
return <div className="ss-shell"><header className="ss-top"><div className="ss-wrap"><div className="ss-brand">SKILL SAGA · REWARDS</div><h1>🎁 Rewards</h1><p>Learn, earn coins and redeem exciting rewards.</p></div></header><main className="ss-main"><section className="ss-wallet"><span>Your Coins</span><b>🪙 {data?.wallet.balance??0}</b><small>Earned {data?.wallet.earned??0} · Spent {data?.wallet.spent??0}</small></section>{error&&<div className="error-box">{error}</div>}<section className="ss-section-head"><h2>Reward Catalogue</h2><span className="ss-eyebrow">LEARN · EARN · REDEEM</span></section><section className="ss-rewards">{(data?.rewards||[]).map(r=><article className="ss-reward" key={r.id}><div className="ss-reward-art">{r.type.toLowerCase().includes("voucher")?"🎟️":r.type.toLowerCase().includes("merch")?"👕":"🎁"}</div><div><b>{r.name}</b><p>{r.description||"A Skill Saga reward."}</p><strong>{r.coinCost} 🪙</strong></div><button className="ss-btn primary" disabled={!!busy||r.coinCost>(data?.wallet.balance??0)} onClick={()=>redeem(r.id)}>{busy===r.id?"Redeeming…":"Redeem"}</button></article>)}{!data?.rewards?.length&&<div className="ss-card"><p>No rewards are available yet.</p></div>}</section><div className="ss-actions"><Link href="/play" className="ss-btn primary">Earn More Coins</Link><Link href="/profile" className="ss-btn">Profile</Link></div></main><LearnerNav active="Profile"/></div>}