"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { RecaptchaVerifier, ConfirmationResult, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPhoneNumber } from "firebase/auth";
import { learnerAuth } from "../../lib/firebase";
export default function LoginPage() {
  const [mode,setMode]=useState<"email"|"phone">("email"); const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[phone,setPhone]=useState(""),[otp,setOtp]=useState("");
  const [confirmation,setConfirmation]=useState<ConfirmationResult|null>(null); const [busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const recaptcha=useRef<RecaptchaVerifier|null>(null);
  useEffect(()=>()=>{recaptcha.current?.clear();},[]);
  function ensureRecaptcha(){if(typeof window==="undefined")return;if(!recaptcha.current)recaptcha.current=new RecaptchaVerifier(learnerAuth,"recaptcha-container",{size:"invisible"});}
  async function sendOtp(){const digits=phone.replace(/\D/g,"");if(!/^91\d{10}$/.test(digits)){setError("Enter a valid Indian mobile number with +91.");return;}setBusy(true);setError("");setMessage("");try{ensureRecaptcha();const result=await signInWithPhoneNumber(learnerAuth,"+"+digits,recaptcha.current!);setConfirmation(result);setMessage("OTP sent. Enter the 6-digit code.");}catch(err:any){recaptcha.current?.clear();recaptcha.current=null;setError(err?.message?.replace("Firebase: ","")||"Unable to send OTP.");}finally{setBusy(false);}}
  async function verifyOtp(e:FormEvent){e.preventDefault();if(!confirmation)return;if(!/^\d{6}$/.test(otp.trim())){setError("Enter the 6-digit OTP.");return;}setBusy(true);setError("");try{await confirmation.confirm(otp.trim());window.location.href="/";}catch(err:any){setError(err?.message?.replace("Firebase: ","")||"Invalid OTP.");}finally{setBusy(false);}}
  async function resetPassword(){if(!email.trim()){setError("Enter your email first.");return;}setBusy(true);setError("");setMessage("");try{await sendPasswordResetEmail(learnerAuth,email.trim());setMessage("Password reset email sent. Check your inbox.");}catch(err:any){setError(err?.message?.replace("Firebase: ","")||"Unable to send reset email.");}finally{setBusy(false);}}
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await signInWithEmailAndPassword(learnerAuth,email.trim(),password);window.location.href="/";}catch(err:any){setError(err?.message?.replace("Firebase: ","")||"Unable to sign in.");}finally{setBusy(false);}}
  return <main className="page-shell narrow"><section className="hero-card"><p className="eyebrow">SKILL SAGA</p><h1>Welcome back</h1><p className="muted">Sign in to access your learning, quizzes, XP and progress.</p></section><div className="auth-switch"><button className={mode==="email"?"active":""} onClick={()=>{setMode("email");setError("");setMessage("");}}>Email</button><button className={mode==="phone"?"active":""} onClick={()=>{setMode("phone");setError("");setMessage("");}}>Mobile OTP</button></div>
{mode==="email"?<form className="panel form-stack" onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="error-box">{error}</div>}{message&&<div className="ss-message">{message}</div>}<button className="primary-button" disabled={busy}>{busy?"Signing in…":"Sign in"}</button><button type="button" className="secondary-button" onClick={()=>void resetPassword()} disabled={busy}>Forgot / Reset Password</button></form>:<form className="panel form-stack" onSubmit={verifyOtp}><label>Mobile number<input value={phone} onChange={e=>setPhone(e.target.value)} type="tel" inputMode="tel" placeholder="+91 9876543210" disabled={!!confirmation} required/></label>{!confirmation?<button type="button" className="primary-button" onClick={()=>void sendOtp()} disabled={busy}>{busy?"Sending OTP…":"Send OTP"}</button>:<><label>6-digit OTP<input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" autoComplete="one-time-code" required/></label><button className="primary-button" disabled={busy}>{busy?"Verifying…":"Verify OTP"}</button><button type="button" className="secondary-button" onClick={()=>{setConfirmation(null);setOtp("");setMessage("");}}>Change number</button></>}{error&&<div className="error-box">{error}</div>}{message&&<div className="ss-message">{message}</div>}</form>}
<div id="recaptcha-container" /><p className="muted small">Learner registration will be connected through the Admin-controlled account flow.</p></main>;}