"use client";
import {useEffect,useState} from "react";
import {onAuthStateChanged} from "firebase/auth";
import {learnerAuth} from "../../lib/firebase";
import {learnerFunction} from "../../lib/learner-api";
import LearnerNav from "../components/LearnerNav";
type Quiz={id:string;title:string;description:string;questionCount:number};type Question={id:string;questionText:string;options:string[];marks:number};type Result={correct:number;total:number;marks:number;totalMarks:number;percentage:number;xpEarned?:number;coinsEarned?:number};
export default function PlayPage(){const [initialQuizId,setInitialQuizId]=useState<string|null>(null);const [quizzes,setQuizzes]=useState<Quiz[]>([]),[quiz,setQuiz]=useState<Quiz|null>(null),[questions,setQuestions]=useState<Question[]>([]),[answers,setAnswers]=useState<number[]>([]),[idx,setIdx]=useState(0),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[token,setToken]=useState(""),[submissionId,setSubmissionId]=useState("");
useEffect(()=>onAuthStateChanged(learnerAuth,async u=>{if(!u){setLoading(false);return;}const t=await u.getIdToken();setToken(t);setSubmissionId(crypto.randomUUID());const p=new URLSearchParams(window.location.search).get("quizId");setInitialQuizId(p);try{if(p){const q=await learnerFunction("getQuizForAttempt",{quizId:p},t);setQuiz(q);setQuestions(q.questions||[]);setAnswers(new Array(q.questions?.length||0).fill(-1));}else{const q=await learnerFunction("listPublishedQuizzes",{},t);setQuizzes(q.items||[]);}}catch(e:any){setError(e.message);}finally{setLoading(false);}}),[]);
async function start(id:string){try{const q=await learnerFunction("getQuizForAttempt",{quizId:id},token);setQuiz(q);setQuestions(q.questions||[]);setAnswers(new Array(q.questions?.length||0).fill(-1));setSubmissionId(crypto.randomUUID());}catch(e:any){setError(e.message);}}
async function submit(){if(!quiz)return;try{const r=await learnerFunction("submitQuizAttempt",{quizId:quiz.id,answers,submissionId},token);setResult(r);}catch(e:any){setError(e.message);}}
if(!learnerAuth.currentUser&&!loading)return <div className="ss-shell"><header className="ss-top"><div className="ss-wrap"><div className="ss-brand">SKILL SAGA · PLAY</div><h1>▶ Practice</h1></div></header><main className="ss-main"><section className="ss-card"><h2>Sign in to play</h2><p>Log in to start quizzes and earn XP.</p></section></main></div>;
return <div className="ss-shell"><header className="ss-top"><div className="ss-wrap"><div className="ss-brand">SKILL SAGA · PRACTICE</div><h1>{result?"🎉 Great Job!":quiz?.title||"Practice"}</h1><p>{result?"Review your result and keep your streak going!":"Challenge yourself and grow your skills."}</p></div></header><main className="ss-main">{error&&<div className="error-box">{error}</div>}{result?<section className="ss-result"><div className="ss-badge">🏆</div><h2>{result.percentage}%</h2><p>You scored {result.correct} out of {result.total}</p><div className="ss-home-stats"><div><b>🪙 +{result.coinsEarned??0}</b><small>Coins</small></div><div><b>⭐ +{result.xpEarned??0}</b><small>XP</small></div><div><b>🔥 +1</b><small>Streak</small></div></div><button className="ss-btn primary" onClick={()=>{setResult(null);setQuiz(null);setIdx(0);}}>Back to Practice</button></section>:quiz?<section className="ss-card"><div className="ss-level-line"><strong>Question {idx+1} of {questions.length}</strong><span>⏱ Practice</span></div><div className="ss-progress"><span style={{width:((idx+1)/Math.max(1,questions.length))*100+"%"}}/></div><h2 style={{marginTop:18}}>{questions[idx]?.questionText}</h2>{questions[idx]?.options.map((o,i)=><button key={i} className={"ss-quiz-option "+(answers[idx]===i?"selected":"")} onClick={()=>setAnswers(a=>a.map((v,j)=>j===idx?i:v))}><b>{String.fromCharCode(65+i)}</b>{o}</button>)}<div className="quiz-actions">{<button className="ss-btn" disabled={idx===0} onClick={()=>setIdx(i=>i-1)}>Previous</button>}{idx<questions.length-1?<button className="ss-btn primary" disabled={answers[idx]<0} onClick={()=>setIdx(i=>i+1)}>Next</button>:<button className="ss-btn primary" disabled={answers.some(a=>a<0)} onClick={submit}>Submit Quiz</button>}</div></section>:<section><div className="ss-section-head"><h2>Choose a Quiz</h2><span className="ss-eyebrow">{quizzes.length} available</span></div><div className="ss-grid">{quizzes.map(q=><button key={q.id} className="ss-card" style={{textAlign:"left",border:0}} onClick={()=>start(q.id)}><span className="ss-eyebrow">{q.questionCount} QUESTIONS</span><h2>{q.title}</h2><p>{q.description||"Test yourself and earn XP."}</p></button>)}{!quizzes.length&&<div className="ss-card"><p>No published quizzes are available yet.</p></div>}</div></section>}</main><LearnerNav active="Play"/></div>}