"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {onAuthStateChanged} from "firebase/auth";
import {learnerAuth} from "../../lib/firebase";
import {learnerFunction} from "../../lib/learner-api";
import LearnerNav from "../components/LearnerNav";
export default function Play(){const [quizzes,setQuizzes]=useState<any[]>([]),[quiz,setQuiz]=useState<any>(null),[q,setQ]=useState(0),[answers,setAnswers]=useState<number[]>([]),[result,setResult]=useState<any>(null),[token,setToken]=useState("");
useEffect(()=>onAuthStateChanged(learnerAuth,async u=>{if(!u)return;const t=await u.getIdToken();setToken(t);try{setQuizzes((await learnerFunction("listPublishedQuizzes",{},t))?.items||[]);}catch{}}),[]);
async function start(id:string){const x=await learnerFunction("getQuizForAttempt",{quizId:id},token);setQuiz(x);setAnswers(new Array(x.questions?.length||0).fill(-1));setQ(0);}
async function submit(){const x=await learnerFunction("submitQuizAttempt",{quizId:quiz.id,answers,submissionId:crypto.randomUUID()},token);setResult(x);}
if(result)return <div className="ss-app"><header className="ss-inner-header"><Link href="/play">‹</Link><b>Quiz Result</b><span>🏆</span></header><main className="ss-page ss-result-page"><div className="ss-confetti">🎉</div><h1>Great Job!</h1><p>You scored {result.correct} out of {result.total}</p><div className="ss-score">{result.percentage}%</div><div className="ss-result-stats"><span>🪙<b>+{result.coinsEarned||0}</b><small>Coins</small></span><span>⭐<b>+{result.xpEarned||0}</b><small>XP</small></span><span>🔥<b>+1</b><small>Streak</small></span></div><Link className="ss-primary wide" href="/play">Review Answers</Link><Link className="ss-secondary wide" href="/">Back to Home</Link></main><LearnerNav active="Play"/></div>;
return <div className="ss-app"><header className="ss-inner-header"><Link href="/">‹</Link><div><b>Practice</b><small>Challenge yourself and grow</small></div><span>⌕</span></header><main className="ss-page">{quiz?<section className="ss-practice"><div className="ss-qtop"><b>Question {q+1} of {quiz.questions.length}</b><span>⏱ 08:15</span></div><div className="ss-bar"><i style={{width:((q+1)/quiz.questions.length)*100+"%"}}/></div><h2>{quiz.questions[q]?.questionText}</h2>{quiz.questions[q]?.options?.map((o:string,i:number)=><button className={"ss-option "+(answers[q]===i?"selected":"")} key={i} onClick={()=>setAnswers(a=>a.map((v,j)=>j===q?i:v))}><b>{String.fromCharCode(65+i)}</b>{o}</button>)}<div className="ss-actions">{q>0&&<button className="ss-secondary" onClick={()=>setQ(q-1)}>Previous</button>}{q<quiz.questions.length-1?<button className="ss-primary" disabled={answers[q]<0} onClick={()=>setQ(q+1)}>Next</button>:<button className="ss-primary" disabled={answers.some(a=>a<0)} onClick={submit}>Submit</button>}</div></section>:<><div className="ss-heading"><b>Choose a Quiz</b><span>View all →</span></div><div className="ss-quiz-list">{quizzes.map(x=><button key={x.id} onClick={()=>start(x.id)}><span>🧪</span><div><b>{x.title}</b><small>{x.questionCount||5} Questions · Easy</small></div><strong>›</strong></button>)}{!quizzes.length&&<div className="ss-empty">Published quizzes will appear here.</div>}</div></>}</main><LearnerNav active="Play"/></div>}