"use client";

import { useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { learnerAuth } from "../../lib/firebase";

type Quiz={id:string;title:string;description:string;questionCount:number};
type Question={id:string;questionText:string;options:string[];marks:number};
type Result={correct:number;total:number;marks:number;totalMarks:number;percentage:number;xpEarned?:number;coinsEarned?:number};
async function call(action:string,data:any,token:string){const r=await fetch("/api/learner-quiz",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({action,data})});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"Request failed.");return p?.data??p;}

export default function PlayPage(){
 const [ready,setReady]=useState(false),[token,setToken]=useState(""),[submissionId,setSubmissionId]=useState(""),[quizzes,setQuizzes]=useState<Quiz[]>([]),[mode,setMode]=useState<"quiz"|"topic"|"competition">("quiz"),[quiz,setQuiz]=useState<Quiz|null>(null),[questions,setQuestions]=useState<Question[]>([]),[answers,setAnswers]=useState<number[]>([]),[index,setIndex]=useState(0),[result,setResult]=useState<Result|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>onAuthStateChanged(learnerAuth,async user=>{setReady(true);if(!user){setLoading(false);return;}try{const t=await user.getIdToken();setToken(t);const p=await call("listPublishedQuizzes",{},t);setQuizzes(p.items||[]);const params=new URLSearchParams(window.location.search);const wanted=params.get("quizId"),topicId=params.get("topicId"),competitionId=params.get("competitionId");
if(competitionId){setMode("competition");const cp=await call("getCompetitionQuiz",{competitionId},t);setQuiz({id:"competition-"+competitionId,title:cp.competition.name,description:cp.competition.description,questionCount:cp.questions.length});setQuestions(cp.questions);setAnswers(Array(cp.questions.length).fill(-1));setIndex(0);}else if(wanted){setMode("quiz");const q=(p.items||[]).find((x:Quiz)=>x.id===wanted);if(q) await openQuizWithToken(q,t);}
else if(topicId){const tp=await call("getTopicPractice",{topicId},t);if((tp.questions||[]).length){setMode("topic");setQuiz({id:"topic-"+topicId,title:tp.topic.name+" Practice",description:"Topic practice",questionCount:tp.questions.length});setQuestions(tp.questions);setAnswers(Array(tp.questions.length).fill(-1));setIndex(0);}else setError("No published questions are available for this topic yet.");}}catch(e:any){setError(e.message||"Unable to load quizzes.");}finally{setLoading(false);}}),[]);
 async function openQuizWithToken(q:Quiz,t:string){setSubmissionId(crypto.randomUUID());setMode("quiz");setLoading(true);setError("");try{const p=await call("getQuizForAttempt",{quizId:q.id},t);setQuiz(p.quiz);setQuestions(p.questions);setAnswers(Array(p.questions.length).fill(-1));setIndex(0);}catch(e:any){setError(e.message);}finally{setLoading(false);}}

 async function openQuiz(q:Quiz){await openQuizWithToken(q,token);}
 async function submit(){setLoading(true);try{const params=new URLSearchParams(window.location.search);const competitionId=params.get("competitionId");const topicId=params.get("topicId");const p=mode==="competition"&&competitionId?await call("submitCompetitionAttempt",{competitionId,answers},token):mode==="topic"&&topicId?await call("submitTopicPractice",{topicId,answers},token):await call("submitQuizAttempt",{quizId:quiz?.id,answers,submissionId},token);setResult(p.result);}catch(e:any){setError(e.message);}finally{setLoading(false);}}
 if(!ready||loading&&!quiz&&!result&&!error)return <main className="page-shell"><div className="panel">Loading…</div></main>;
 if(!learnerAuth.currentUser)return <main className="page-shell"><section className="hero-card"><p className="eyebrow">PLAY</p><h1>Sign in to play</h1><p className="muted">Your attempts, XP and rewards are tied to your learner account.</p><a className="primary-button" href="/login">Sign in</a></section></main>;
 if(!quiz)return <main className="page-shell"><section className="hero-card"><p className="eyebrow">🎮 PLAY</p><h1>Pick a challenge!</h1><p className="muted">Choose a challenge, test yourself and collect XP + coins. You&apos;ve got this! 💪</p></section>{error&&<div className="error-box">{error}</div>}<div className="card-grid">{quizzes.map(q=><button className="panel action-card" key={q.id} onClick={()=>openQuiz(q)}><strong>{q.title}</strong><span>{q.questionCount} questions</span><span>{q.description||"Ready when you are."}</span></button>)}</div></main>;
 if(result)return <main className="page-shell"><section className="result-card"><p className="eyebrow">🎉 QUIZ COMPLETE</p><h1>{result.percentage}%</h1><p>{result.correct} / {result.total} correct · {result.marks} / {result.totalMarks} marks</p><div className="stat-grid">{result.xpEarned!==undefined&&<div><strong>+{result.xpEarned}</strong><span>XP</span></div>}{result.coinsEarned!==undefined&&<div><strong>+{result.coinsEarned}</strong><span>Coins</span></div>}{result.xpEarned===undefined&&result.coinsEarned===undefined&&<div><strong>🏆</strong><span>Competition result recorded</span></div>}</div><button className="primary-button" onClick={()=>{setQuiz(null);setResult(null)}}>🚀 Try another challenge</button></section></main>;
 const q=questions[index],selected=answers[index];
 return <main className="page-shell"><section className="quiz-header"><div><p className="eyebrow">🧠 CHALLENGE</p><h1>{quiz.title}</h1></div><span>{index+1} / {questions.length}</span></section><div className="progress-bar"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div><section className="panel quiz-card"><p className="muted">Question {index+1}</p><h2>{q.questionText}</h2><div className="options">{q.options.map((o,i)=><button key={i} className={selected===i?"quiz-option selected":"quiz-option"} onClick={()=>setAnswers(a=>a.map((v,n)=>n===index?i:v))}><b>{String.fromCharCode(65+i)}</b>{o}</button>)}</div><div className="quiz-actions">{index>0&&<button className="secondary-button" onClick={()=>setIndex(index-1)}>Previous</button>}{index<questions.length-1?<button className="primary-button" disabled={selected<0} onClick={()=>setIndex(index+1)}>Next</button>:<button className="primary-button" disabled={selected<0||loading} onClick={submit}>{loading?"Submitting…":"Submit quiz"}</button>}</div></section>{error&&<div className="error-box">{error}</div>}</main>;
}