"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {onAuthStateChanged} from "firebase/auth";
import {learnerAuth} from "../../lib/firebase";
import {learnerFunction} from "../../lib/learner-api";
import LearnerNav from "../components/LearnerNav";
type Data={summary:{attempts:number;correct:number;answered:number;accuracy:number;xp:number;coins:number;level:number;streak:number};recentAttempts:any[]};
export default function Progress(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState("");
useEffect(()=>onAuthStateChanged(learnerAuth,async u=>{if(!u)return;try{setData(await learnerFunction("getLearnerProgress",{},await u.getIdToken()));}catch(e:any){setError(e.message);}}),[]);
const s=data?.summary;return <div className="ss-shell"><header className="ss-top"><div className="ss-wrap"><div className="ss-brand">SKILL SAGA · PROGRESS</div><h1>📊 My Progress</h1><p>See how your learning journey is growing.</p></div></header><main className="ss-main">{error&&<div className="error-box">{error}</div>}<section className="ss-progress-hero"><span>Current Level</span><b>Level {s?.level??1}</b><div className="ss-progress"><span style={{width:Math.min(100,((s?.xp??0)%500)/5)+"%"}}/></div><small>{(s?.xp??0)%500} / 500 XP to next level</small></section><section className="ss-home-stats"><div><b>⭐ {s?.xp??0}</b><small>XP</small></div><div><b>🔥 {s?.streak??0}</b><small>Streak</small></div><div><b>🎯 {s?.accuracy??0}%</b><small>Accuracy</small></div></section><section className="ss-card"><h2>Learning summary</h2><div className="ss-stat-list"><p><span>Quizzes attempted</span><b>{s?.attempts??0}</b></p><p><span>Questions answered</span><b>{s?.answered??0}</b></p><p><span>Correct answers</span><b>{s?.correct??0}</b></p><p><span>Coins earned</span><b>🪙 {s?.coins??0}</b></p></div></section><div className="ss-actions"><Link href="/learn" className="ss-btn primary">Continue Learning</Link><Link href="/play" className="ss-btn">Practice</Link></div></main><LearnerNav active="Profile"/></div>}