import {getFirestore,FieldValue} from "firebase-admin/firestore";
import {onCall,HttpsError,type CallableRequest} from "firebase-functions/v2/https";
const ROLES=new Set(["super_admin","admin"]);
function auth(r:CallableRequest<unknown>){const uid=r.auth?.uid,role=r.auth?.token.role;if(!uid)throw new HttpsError("unauthenticated","Administrator authentication is required.");if(typeof role!=="string"||!ROLES.has(role))throw new HttpsError("permission-denied","You are not authorized to manage automation.");return{uid,role};}
const text=(v:unknown)=>typeof v==="string"?v.trim():"";
function validate(raw:any){const name=text(raw.name);if(!name)throw new HttpsError("invalid-argument","Automation name is required.");const type=text(raw.type).toLowerCase();if(!["daily_quiz","weekly_quiz","notification"].includes(type))throw new HttpsError("invalid-argument","Invalid automation type.");const action=text(raw.action);if(!action)throw new HttpsError("invalid-argument","Automation action is required.");const schedule=text(raw.schedule)||"daily";const enabled=Boolean(raw.enabled);return{name,type,action,schedule,enabled,active:raw.active===undefined?enabled:Boolean(raw.active)};}
function audit(uid:string,role:string,action:string,id:string){return{actorUid:uid,actorRole:role,action,collection:"automationRules",documentId:id,createdAt:FieldValue.serverTimestamp()};}
export const listAutomationRules=onCall(async r=>{auth(r);const s=await getFirestore().collection("automationRules").limit(500).get();const items=s.docs.map(d=>({id:d.id,...d.data()}));items.sort((a:any,b:any)=>String(a.name??"").localeCompare(String(b.name??"")));return{items};});
export const createAutomationRule=onCall(async r=>{const{uid,role}=auth(r);const data=validate((r.data as any)?.data??{});const db=getFirestore(),ref=db.collection("automationRules").doc();await ref.set({...data,createdBy:uid,updatedBy:uid,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,"CREATE",ref.id));return{id:ref.id};});
export const updateAutomationRule=onCall(async r=>{const{uid,role}=auth(r);const p=r.data as any,id=text(p?.id);if(!id)throw new HttpsError("invalid-argument","id is required.");const data=validate(p?.data??{});const db=getFirestore(),ref=db.collection("automationRules").doc(id);if(!(await ref.get()).exists)throw new HttpsError("not-found","Automation rule was not found.");await ref.update({...data,updatedBy:uid,updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,"UPDATE",id));return{success:true};});
export const setAutomationEnabled=onCall(async r=>{const{uid,role}=auth(r);const p=r.data as any,id=text(p?.id);if(!id)throw new HttpsError("invalid-argument","id is required.");const enabled=Boolean(p?.enabled);const db=getFirestore(),ref=db.collection("automationRules").doc(id);if(!(await ref.get()).exists)throw new HttpsError("not-found","Automation rule was not found.");await ref.update({enabled,active:enabled,updatedBy:uid,updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,enabled?"ENABLE":"DISABLE",id));return{success:true};});