import {getFirestore,FieldValue} from "firebase-admin/firestore";
import {onCall,HttpsError,type CallableRequest} from "firebase-functions/v2/https";
const ROLES=new Set(["super_admin","admin","moderator","support"]);
function auth(r:CallableRequest<unknown>){const uid=r.auth?.uid,role=r.auth?.token.role;if(!uid)throw new HttpsError("unauthenticated","Administrator authentication is required.");if(typeof role!=="string"||!ROLES.has(role))throw new HttpsError("permission-denied","You are not authorized to manage community moderation.");return{uid,role};}
const text=(v:unknown)=>typeof v==="string"?v.trim():"";
function audit(uid:string,role:string,action:string,id:string){return{actorUid:uid,actorRole:role,action,collection:"communityPosts",documentId:id,createdAt:FieldValue.serverTimestamp()};}
export const listCommunityPosts=onCall(async r=>{auth(r);const s=await getFirestore().collection("communityPosts").limit(500).get();const items=s.docs.map(d=>({id:d.id,...d.data()}));items.sort((a:any,b:any)=>String(b.createdAt??"").localeCompare(String(a.createdAt??"")));return{items};});
export const createCommunityPost=onCall(async r=>{const{uid,role}=auth(r);const p=(r.data as any)?.data??{};const content=text(p.content);if(!content)throw new HttpsError("invalid-argument","Post content is required.");const db=getFirestore(),ref=db.collection("communityPosts").doc();await ref.set({content,status:"pending",active:true,createdBy:uid,createdAt:FieldValue.serverTimestamp(),updatedBy:uid,updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,"CREATE",ref.id));return{id:ref.id};});
export const moderateCommunityPost=onCall(async r=>{const{uid,role}=auth(r);const p=r.data as any,id=text(p?.id),status=text(p?.status).toLowerCase();if(!id)throw new HttpsError("invalid-argument","id is required.");if(!["approved","rejected","pending"].includes(status))throw new HttpsError("invalid-argument","Invalid moderation status.");const db=getFirestore(),ref=db.collection("communityPosts").doc(id);if(!(await ref.get()).exists)throw new HttpsError("not-found","Community post was not found.");await ref.update({status,active:status!=="rejected",updatedBy:uid,updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,status.toUpperCase(),id));return{success:true};});
export const archiveCommunityPost=onCall(async r=>{const{uid,role}=auth(r),id=text((r.data as any)?.id);if(!id)throw new HttpsError("invalid-argument","id is required.");const db=getFirestore(),ref=db.collection("communityPosts").doc(id);if(!(await ref.get()).exists)throw new HttpsError("not-found","Community post was not found.");await ref.update({active:false,updatedBy:uid,updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,"ARCHIVE",id));return{success:true};});