import { getFirestore, FieldValue } from "firebase-admin/firestore";
import { onCall, HttpsError, type CallableRequest } from "firebase-functions/v2/https";
function learner(request: CallableRequest<unknown>){const uid=request.auth?.uid;if(!uid||request.auth?.token.role!=="learner")throw new HttpsError("permission-denied","Only learner accounts can use community.");return uid;}
const text=(v:unknown)=>typeof v==="string"?v.trim():"";
export const listLearnerCommunity=onCall(async request=>{learner(request);const snap=await getFirestore().collection("communityPosts").where("active","==",true).where("status","==","approved").limit(100).get();const items=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a:any,b:any)=>String(b.createdAt?.toMillis?.()??"").localeCompare(String(a.createdAt?.toMillis?.()??"")));return{items};});
export const createLearnerCommunityPost=onCall(async request=>{const uid=learner(request),content=text((request.data as any)?.content);if(!content)throw new HttpsError("invalid-argument","Post content is required.");if(content.length>1000)throw new HttpsError("invalid-argument","Post must be 1000 characters or less.");const ref=getFirestore().collection("communityPosts").doc();await ref.set({content,status:"pending",active:true,createdBy:uid,createdByRole:"learner",createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});return{id:ref.id,status:"pending"};});
export const addCommunityComment=onCall(async request=>{const uid=learner(request),postId=text((request.data as any)?.postId),content=text((request.data as any)?.content);if(!postId||!content)throw new HttpsError("invalid-argument","postId and content are required.");if(content.length>500)throw new HttpsError("invalid-argument","Comment must be 500 characters or less.");const post=await getFirestore().collection("communityPosts").doc(postId).get();if(!post.exists||post.data()?.active!==true||post.data()?.status!=="approved")throw new HttpsError("not-found","Community post was not found.");const ref=getFirestore().collection("communityPosts").doc(postId).collection("comments").doc();await ref.set({content,createdBy:uid,createdByRole:"learner",createdAt:FieldValue.serverTimestamp(),active:true});return{id:ref.id};});
export const listCommunityComments=onCall(async request=>{learner(request);const postId=text((request.data as any)?.postId);if(!postId)throw new HttpsError("invalid-argument","postId is required.");const snap=await getFirestore().collection("communityPosts").doc(postId).collection("comments").where("active","==",true).limit(100).get();return{items:snap.docs.map(d=>({id:d.id,...d.data()})).sort((a:any,b:any)=>String(a.createdAt?.toMillis?.()??"").localeCompare(String(b.createdAt?.toMillis?.()??"")))}};);
export const reportCommunityPost=onCall(async request=>{const uid=learner(request),postId=text((request.data as any)?.postId),reason=text((request.data as any)?.reason);if(!postId||!reason)throw new HttpsError("invalid-argument","postId and reason are required.");await getFirestore().collection("communityReports").doc().set({postId,reason:reason.slice(0,300),reportedBy:uid,status:"open",createdAt:FieldValue.serverTimestamp()});return{success:true};});
