import {getFirestore,FieldValue} from "firebase-admin/firestore";
import {onCall,HttpsError,type CallableRequest} from "firebase-functions/v2/https";
const ROLES=new Set(["super_admin","admin","content_manager"]);
function auth(r:CallableRequest<unknown>){const uid=r.auth?.uid,role=r.auth?.token.role;if(!uid)throw new HttpsError("unauthenticated","Administrator authentication is required.");if(typeof role!=="string"||!ROLES.has(role))throw new HttpsError("permission-denied","You are not authorized to manage competitions.");return{uid,role};}
const text=(v:unknown)=>typeof v==="string"?v.trim():"";
function validate(raw:any){const name=text(raw.name);if(!name)throw new HttpsError("invalid-argument","Competition name is required.");const status=text(raw.status).toLowerCase()||"draft";if(!["draft","published"].includes(status))throw new HttpsError("invalid-argument","Status must be Draft or Published.");const entryType=text(raw.entryType).toLowerCase()||"free";if(!["free","paid"].includes(entryType))throw new HttpsError("invalid-argument","Entry type must be Free or Paid.");const entryFee=Number(raw.entryFee??0);if(entryType==="paid"&&(!Number.isFinite(entryFee)||entryFee<=0))throw new HttpsError("invalid-argument","Paid competitions require a positive entry fee.");const max=Number(raw.maxParticipants);if(!Number.isInteger(max)||max<1)throw new HttpsError("invalid-argument","Maximum participants must be at least 1.");const startAtMs=raw.startAtMs==null||raw.startAtMs===""?null:Number(raw.startAtMs);const endAtMs=raw.endAtMs==null||raw.endAtMs===""?null:Number(raw.endAtMs);if(startAtMs!==null&&!Number.isFinite(startAtMs))throw new HttpsError("invalid-argument","startAtMs must be a valid timestamp.");if(endAtMs!==null&&!Number.isFinite(endAtMs))throw new HttpsError("invalid-argument","endAtMs must be a valid timestamp.");if(startAtMs!==null&&endAtMs!==null&&endAtMs<=startAtMs)throw new HttpsError("invalid-argument","endAtMs must be later than startAtMs.");return{name,description:text(raw.description),quizId:text(raw.quizId),boardId:text(raw.boardId),classId:text(raw.classId),maxParticipants:max,entryType,entryFee:entryType==="paid"?entryFee:0,startAtMs,endAtMs,status,active:raw.active===undefined?true:Boolean(raw.active)};}
async function ensure(raw:any,published:boolean){const db=getFirestore();if(!raw.quizId)throw new HttpsError("invalid-argument","A quiz is required.");const q=await db.collection("quizzes").doc(raw.quizId).get();if(!q.exists)throw new HttpsError("not-found","Selected quiz was not found.");if(published&&q.data()?.active!==true)throw new HttpsError("failed-precondition","Published competitions require an active quiz.");}
function audit(uid:string,role:string,action:string,id:string){return{actorUid:uid,actorRole:role,action,collection:"competitions",documentId:id,createdAt:FieldValue.serverTimestamp()};}
export const listCompetitions=onCall(async r=>{auth(r);const s=await getFirestore().collection("competitions").limit(500).get();const items=s.docs.map(d=>({id:d.id,...d.data()}));items.sort((a:any,b:any)=>String(a.name??"").localeCompare(String(b.name??"")));return{items};});
export const createCompetition=onCall(async r=>{const{uid,role}=auth(r);const data=validate((r.data as any)?.data??{});await ensure(data,false);const db=getFirestore(),ref=db.collection("competitions").doc();await ref.set({...data,createdBy:uid,updatedBy:uid,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,"CREATE",ref.id));return{id:ref.id};});
export const updateCompetition=onCall(async r=>{const{uid,role}=auth(r);const p=r.data as any,id=text(p?.id);if(!id)throw new HttpsError("invalid-argument","id is required.");const data=validate(p?.data??{});await ensure(data,data.status==="published");const db=getFirestore(),ref=db.collection("competitions").doc(id);if(!(await ref.get()).exists)throw new HttpsError("not-found","Competition was not found.");await ref.update({...data,updatedBy:uid,updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,"UPDATE",id));return{success:true};});
export const archiveCompetition=onCall(async r=>{const{uid,role}=auth(r),id=text((r.data as any)?.id);if(!id)throw new HttpsError("invalid-argument","id is required.");const db=getFirestore(),ref=db.collection("competitions").doc(id);if(!(await ref.get()).exists)throw new HttpsError("not-found","Competition was not found.");await ref.update({active:false,status:"draft",updatedBy:uid,updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,"ARCHIVE",id));return{success:true};});