import {getFirestore,FieldValue} from "firebase-admin/firestore";
import {onCall,HttpsError,type CallableRequest} from "firebase-functions/v2/https";
const ROLES=new Set(["super_admin","admin","support","moderator"]);
function auth(r:CallableRequest<unknown>){const uid=r.auth?.uid,role=r.auth?.token.role;if(!uid)throw new HttpsError("unauthenticated","Administrator authentication is required.");if(typeof role!=="string"||!ROLES.has(role))throw new HttpsError("permission-denied","You are not authorized to manage notifications.");return{uid,role};}
const text=(v:unknown)=>typeof v==="string"?v.trim():"";
function validate(raw:any){const title=text(raw.title),message=text(raw.message),type=text(raw.type).toLowerCase(),audience=text(raw.audience).toLowerCase();if(!title)throw new HttpsError("invalid-argument","Notification title is required.");if(!message)throw new HttpsError("invalid-argument","Notification message is required.");if(!["announcement","reminder","achievement","system"].includes(type))throw new HttpsError("invalid-argument","Invalid notification type.");if(!["all","learners","parents","teachers"].includes(audience))throw new HttpsError("invalid-argument","Invalid audience.");return{title,message,type,audience,active:raw.active===undefined?true:Boolean(raw.active)};}
function audit(uid:string,role:string,action:string,id:string){return{actorUid:uid,actorRole:role,action,collection:"notificationTemplates",documentId:id,createdAt:FieldValue.serverTimestamp()};}
export const listNotificationTemplates=onCall(async r=>{auth(r);const s=await getFirestore().collection("notificationTemplates").limit(500).get();const items=s.docs.map(d=>({id:d.id,...d.data()}));items.sort((a:any,b:any)=>String(a.title??"").localeCompare(String(b.title??"")));return{items};});
export const createNotificationTemplate=onCall(async r=>{const{uid,role}=auth(r);const data=validate((r.data as any)?.data??{});const db=getFirestore(),ref=db.collection("notificationTemplates").doc();await ref.set({...data,createdBy:uid,updatedBy:uid,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,"CREATE",ref.id));return{id:ref.id};});
export const updateNotificationTemplate=onCall(async r=>{const{uid,role}=auth(r);const p=r.data as any,id=text(p?.id);if(!id)throw new HttpsError("invalid-argument","id is required.");const data=validate(p?.data??{});const db=getFirestore(),ref=db.collection("notificationTemplates").doc(id);if(!(await ref.get()).exists)throw new HttpsError("not-found","Notification template was not found.");await ref.update({...data,updatedBy:uid,updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,"UPDATE",id));return{success:true};});
export const archiveNotificationTemplate=onCall(async r=>{const{uid,role}=auth(r),id=text((r.data as any)?.id);if(!id)throw new HttpsError("invalid-argument","id is required.");const db=getFirestore(),ref=db.collection("notificationTemplates").doc(id);if(!(await ref.get()).exists)throw new HttpsError("not-found","Notification template was not found.");await ref.update({active:false,updatedBy:uid,updatedAt:FieldValue.serverTimestamp()});await db.collection("auditLogs").doc().set(audit(uid,role,"ARCHIVE",id));return{success:true};});