"use client";
import{useEffect,useState}from"react";import{onAuthStateChanged,signInWithEmailAndPassword,signOut}from"firebase/auth";import{teacherAuth}from"./lib/firebase";import{teacherFunction}from"./lib/api";

const tabs=["dashboard","classes","students","assignments","content","tests","analytics","reports","profile"];
const emptyMaterial={title:"",description:"",type:"pdf",boardId:"",classId:"",subjectId:"",fileUrl:""};
const emptyAssignment={title:"",description:"",resourceType:"quiz",resourceId:"",targetType:"learner",targetId:"",dueAtMs:""};

export default function Teacher(){const[tab,setTab]=useState("dashboard"),[data,setData]=useState<any>({}),[user,setUser]=useState<any>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[items,setItems]=useState<any[]>([]),[form,setForm]=useState<any>(emptyMaterial),[assignment,setAssignment]=useState<any>(emptyAssignment),[saving,setSaving]=useState(false),[message,setMessage]=useState("");

useEffect(()=>onAuthStateChanged(teacherAuth,async u=>{setUser(u);if(!u)return;try{const t=await u.getIdToken();setData(await teacherFunction("getTeacherDashboard",{},t))}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard.")}}),[]);

async function token(){if(!user)throw Error("Not signed in.");return user.getIdToken()}
async function load(kind:string){setError("");setMessage("");try{const t=await token();const action=kind==="assignments"?"listTeacherAssignments":"listTeacherMaterials";const r=await teacherFunction(action,{},t);setItems(r.items||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load data.")}}
async function openTab(x:string){setTab(x);if(x==="assignments"||x==="content")await load(x);if(x==="tests"||x==="reports"){try{const t=await token();const r=await teacherFunction("listTeacherResults",{},t);setItems(r.items||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load results.")}}}
async function login(e:any){e.preventDefault();setError("");setBusy(true);try{await signInWithEmailAndPassword(teacherAuth,email.trim(),password)}catch(e){setError(e instanceof Error?e.message:"Sign in failed.")}finally{setBusy(false)}}
async function saveMaterial(e:any){e.preventDefault();setSaving(true);setError("");setMessage("");try{const t=await token();if(form.id)await teacherFunction("updateTeacherMaterial",{id:form.id,data:form},t);else await teacherFunction("createTeacherMaterial",form,t);setForm(emptyMaterial);setMessage("Learning material saved as draft.");await load("content")}catch(e){setError(e instanceof Error?e.message:"Unable to save material.")}finally{setSaving(false)}}
async function saveAssignment(e:any){e.preventDefault();setSaving(true);setError("");setMessage("");try{const t=await token();await teacherFunction("createAssignment",{data:{...assignment,dueAtMs:assignment.dueAtMs?Number(assignment.dueAtMs):null}},t);setAssignment(emptyAssignment);setMessage("Assignment created successfully.");await load("assignments")}catch(e){setError(e instanceof Error?e.message:"Unable to create assignment.")}finally{setSaving(false)}}

if(!user)return <main className="teacher-login"><section className="login-card"><div className="brand">Skill Saga <span>Teacher</span></div><h1>Teacher Sign In</h1><p>Manage classes, assignments and student learning.</p><form onSubmit={login}><input type="email" placeholder="Teacher email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary" disabled={busy}>{busy?"Signing in…":"Sign In"}</button></form>{error&&<div className="error">{error}</div>}</section></main>;

return <main className="teacher-shell"><header><div><div className="brand">Skill Saga <span>Teacher</span></div><p>Teach smarter. Track progress. Inspire learning.</p></div><button onClick={()=>signOut(teacherAuth)}>Sign out</button></header><nav>{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>openTab(x)} key={x}>{x}</button>)}</nav>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<section><h1>{tab==="dashboard"?"Teacher Dashboard":tab[0].toUpperCase()+tab.slice(1)}</h1>
{tab==="dashboard"&&<><div className="grid"><article><b>{data.classesCount??0}</b><span>Classes</span></article><article><b>{data.studentsCount??0}</b><span>Students</span></article><article><b>{data.assignmentsCount??0}</b><span>Assignments</span></article><article><b>{data.averageAccuracy??0}%</b><span>Average Accuracy</span></article></div><div className="panel"><h2>Teacher Workspace</h2><p>Use Assignments to give quizzes/content to learners and Learning Content to prepare your own notes, PDFs, videos or links.</p><div className="quick"><button onClick={()=>openTab("assignments")}>+ Create Assignment</button><button onClick={()=>openTab("content")}>+ Add Learning Content</button></div></div></>}
{tab==="assignments"&&<div className="workspace"><div className="panel"><h2>Create Assignment</h2><form className="form-grid" onSubmit={saveAssignment}><input placeholder="Assignment title" value={assignment.title} onChange={e=>setAssignment({...assignment,title:e.target.value})} required/><select value={assignment.resourceType} onChange={e=>setAssignment({...assignment,resourceType:e.target.value})}><option value="quiz">Quiz</option><option value="content">Learning Content</option></select><input placeholder="Resource ID" value={assignment.resourceId} onChange={e=>setAssignment({...assignment,resourceId:e.target.value})} required/><select value={assignment.targetType} onChange={e=>setAssignment({...assignment,targetType:e.target.value})}><option value="learner">Learner</option><option value="class">Class</option><option value="school">School</option></select><input placeholder="Target ID" value={assignment.targetId} onChange={e=>setAssignment({...assignment,targetId:e.target.value})} required/><input type="datetime-local" value={assignment.dueAtMs?new Date(Number(assignment.dueAtMs)).toISOString().slice(0,16):""} onChange={e=>setAssignment({...assignment,dueAtMs:e.target.value?Date.parse(e.target.value):""})}/><textarea placeholder="Description" value={assignment.description} onChange={e=>setAssignment({...assignment,description:e.target.value})}/><button className="primary" disabled={saving}>{saving?"Saving…":"Create Assignment"}</button></form></div><div className="panel"><h2>Your Assignments</h2>{items.length===0?<p>No teacher assignments yet.</p>:<div className="list">{items.map(x=><div className="row" key={x.id}><div><b>{x.title}</b><small>{x.resourceType} → {x.targetType}:{x.targetId}</small></div><span>{x.active?"Active":"Archived"}</span></div>)}</div>}</div></div>}
{(tab==="tests"||tab==="reports")&&<div className="panel"><h2>Student Results</h2><p>Results from quizzes assigned by you. Scores are calculated securely on the server.</p>{items.length===0?<p>No student results yet.</p>:<div className="list">{items.map(x=><div className="row" key={x.id}><div><b>{x.learnerName}</b><small>{x.quizTitle} · {x.correct}/{x.total} correct</small></div><strong>{x.percentage}%</strong></div>)}</div>}</div>}{tab==="content"&&<div className="workspace"><div className="panel"><h2>Create Learning Content</h2><form className="form-grid" onSubmit={saveMaterial}><input placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="pdf">PDF</option><option value="video">Video</option><option value="article">Article</option><option value="link">Link</option></select><input placeholder="Board ID" value={form.boardId} onChange={e=>setForm({...form,boardId:e.target.value})}/><input placeholder="Class ID" value={form.classId} onChange={e=>setForm({...form,classId:e.target.value})}/><input placeholder="Subject ID" value={form.subjectId} onChange={e=>setForm({...form,subjectId:e.target.value})}/><input placeholder="File / Video / Link URL" value={form.fileUrl} onChange={e=>setForm({...form,fileUrl:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="primary" disabled={saving}>{saving?"Saving…":"Save Draft"}</button></form></div><div className="panel"><h2>Your Content</h2>{items.length===0?<p>No teacher content yet.</p>:<div className="list">{items.map(x=><div className="row" key={x.id}><div><b>{x.title}</b><small>{x.type} · {x.classId||"Class not mapped"} · {x.status}</small></div><button onClick={()=>setForm({...emptyMaterial,...x})}>Edit</button></div>)}</div>}</div></div>}
{["classes","students","tests","analytics","reports","profile"].includes(tab)&&<div className="panel"><h2>{tab==="classes"?"My Classes":tab==="students"?"My Students":tab==="tests"?"Tests & Schedule":tab==="analytics"?"Performance Analytics":tab==="reports"?"Class Reports":"Teacher Profile"}</h2><p>This module is the next data-management layer. The authenticated teacher workspace is connected and ready; no mock records are shown.</p>{tab==="analytics"&&<div className="grid"><article><b>{data.averageAccuracy??0}%</b><span>Accuracy</span></article><article><b>{data.materialsCount??0}</b><span>Materials</span></article><article><b>{data.assignmentsCount??0}</b><span>Assignments</span></article></div>}</div>}</section></main>}
