"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {onAuthStateChanged} from "firebase/auth";
import {learnerAuth} from "../../lib/firebase";
import {learnerFunction} from "../../lib/learner-api";
import LearnerNav from "../components/LearnerNav";
type Competition={id:string;name:string;description:string;maxParticipants:number;entryType:string;entryFee:number;participants:number;joined:boolean};
type Row={rank:number;learnerId:string;marks:number;percentage:number};
export default function Compete(){
 const [items,setItems]=useState<Competition[]>([]),[rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<Competition|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>onAuthStateChanged(learnerAuth,async u=>{if(!u)return;try{setItems((await learnerFunction("listPublishedCompetitions",{},await u.getIdToken()))?.items||[]);}catch(e:any){setError(e.message);}}),[]);
 async function join(c:Competition){if(!learnerAuth.currentUser)return;setBusy(true);try{await learnerFunction("joinCompetition",{competitionId:c.id},await learnerAuth.currentUser.getIdToken());setItems(x=>x.map(v=>v.id===c.id?{...v,joined:true,participants:v.participants+1}:v));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function leaderboard(c:Competition){if(!learnerAuth.currentUser)return;try{setRows((await learnerFunction("getCompetitionLeaderboard",{competitionId:c.id},await learnerAuth.currentUser.getIdToken()))?.items||[]);setSelected(c);}catch(e:any){setError(e.message);}}
 return <div className="ss-shell"><header className="ss-top"><div className="ss-wrap"><div className="ss-brand">SKILL SAGA · COMPETE</div><h1>🏆 Compete</h1><p>Challenge yourself and climb the leaderboard!</p></div></header><main className="ss-main"><div className="ss-tabs"><button className="active">Live</button><button>Upcoming</button><button>My Competitions</button></div>{error&&<div className="error-box">{error}</div>}{items.length===0?<section className="ss-card"><h2>No competitions yet</h2><p>Published competitions will appear here.</p></section>:<section className="ss-competition-list">{items.map(c=><article className="ss-competition" key={c.id}><div className="ss-comp-icon">{c.name.toLowerCase().includes("science")?"🧪":"🏆"}</div><div className="ss-comp-main"><span className="ss-pill">{c.entryType==="paid"?"PAID":"FREE"}</span><h2>{c.name}</h2><p>{c.description||"Test your skills against other learners."}</p><small>👥 {c.participants}/{c.maxParticipants} joined</small><div className="ss-actions">{c.joined?<Link href={"/play?competitionId="+c.id} className="ss-btn primary">Start Competition</Link>:c.entryType==="paid"?<button className="ss-btn" disabled>Payment required</button>:<button className="ss-btn primary" disabled={busy} onClick={()=>join(c)}>Join Free</button>}<button className="ss-btn" onClick={()=>leaderboard(c)}>Leaderboard</button></div></div></article>)}</section>}{selected&&<section className="ss-card" style={{marginTop:16}}><span className="ss-eyebrow">LEADERBOARD</span><h2>{selected.name}</h2>{rows.length?rows.map(r=><div className="ss-rank-row" key={r.learnerId}><b>#{r.rank}</b><span>{r.learnerId===learnerAuth.currentUser?.uid?"You":"Learner"}</span><strong>{r.marks} · {r.percentage}%</strong></div>):<p>No submissions yet.</p>}</section>}</main><LearnerNav active="Compete"/></div>;
}