"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {onAuthStateChanged} from "firebase/auth";
import {learnerAuth} from "../../lib/firebase";
import { learnerFunction } from "../../lib/learner-api";
import LearnerNav from "../components/LearnerNav";
type Competition={id:string;name:string;description:string;maxParticipants:number;entryType:string;entryFee:number;participants:number;joined:boolean};
type Row={rank:number;learnerId:string;correct:number;marks:number;totalMarks:number;percentage:number};
async function call(action:string,data:any,token:string){return learnerFunction(action,data,token);}`,"Content-Type":"application/json"},body:JSON.stringify({action,data})});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"Request failed.");return p?.data??p;}
export default function Compete(){const[token,setToken]=useState(""),[items,setItems]=useState<Competition[]>([]),[selected,setSelected]=useState<Competition|null>(null),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
useEffect(()=>onAuthStateChanged(learnerAuth,async user=>{if(!user)return;try{const t=await user.getIdToken();setToken(t);const p=await call("listPublishedCompetitions",{},t);setItems(p.items||[]);}catch(e:any){setError(e.message);}}),[]);
async function join(c:Competition){setBusy(true);setError("");try{await call("joinCompetition",{competitionId:c.id},token);setItems(x=>x.map(v=>v.id===c.id?{...v,joined:true,participants:v.participants+1}:v));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
async function leaderboard(c:Competition){setBusy(true);setError("");try{const p=await call("getCompetitionLeaderboard",{competitionId:c.id},token);setRows(p.items||[]);setSelected(c);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
return <div className="ss-shell"><header className="ss-top"><div className="ss-wrap"><div className="ss-brand">SKILL SAGA · COMPETE</div><h1>Competitions</h1><p>Join published challenges, complete the quiz and view the leaderboard.</p></div></header><main className="ss-main">{error&&<div className="ss-card"><p>{error}</p></div>}{items.length===0?<div className="ss-card"><h2>No competitions available</h2><p>Published competitions will appear here when they are opened.</p></div>:<div className="ss-grid">{items.map(c=><div className="ss-card" key={c.id}><span className="ss-eyebrow">{c.entryType==="paid"?`Paid · ₹${c.entryFee}`:"Free"}</span><h2>{c.name}</h2><p>{c.description||"Test your skills against other learners."}</p><p style={{marginTop:8}}>{c.participants}/{c.maxParticipants} participants</p><div className="ss-actions">{c.joined?<Link href={`/play?competitionId=${c.id}`} className="ss-btn primary">Start Competition</Link>:c.entryType==="paid"?<button className="ss-btn" disabled>Payment required</button>:<button className="ss-btn primary" disabled={busy||c.participants>=c.maxParticipants} onClick={()=>join(c)}>{busy?"Joining…":"Join Free"}</button>}<button className="ss-btn" onClick={()=>leaderboard(c)}>Leaderboard</button></div></div>)}</div>}{selected&&<section style={{marginTop:20}}><div className="ss-card"><span className="ss-eyebrow">Leaderboard</span><h2>{selected.name}</h2>{rows.length===0?<p>No submissions yet.</p>:rows.map(r=><div key={r.learnerId} style={{display:"flex",justifyContent:"space-between",padding:"11px 0",borderTop:"1px solid #e7ebf2"}}><span>#{r.rank} · {r.learnerId===learnerAuth.currentUser?.uid?"You":"Learner"}</span><strong>{r.marks} marks · {r.percentage}%</strong></div>)}</div></section>}<div className="ss-actions"><Link href="/play" className="ss-btn">Practice Quiz</Link><Link href="/" className="ss-btn">Home</Link></div></main><Nav/></div>}
function Nav(){return <LearnerNav active="Compete"/>}