"use client";
import{useEffect,useState}from"react";import{onAuthStateChanged,signInWithEmailAndPassword,signOut}from"firebase/auth";import{auth}from"./lib/firebase";

async function call(action:string,token:string,data:any={}){const r=await fetch("/api/guardian",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({action,data})});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"Request failed");return p?.data??p;}

export default function App(){
 const[user,setUser]=useState<any>(null),[token,setToken]=useState(""),[role,setRole]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState(""),[learners,setLearners]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);if(u){const t=await u.getIdToken();const claims=await u.getIdTokenResult();setRole(claims.claims.role==="teacher"?"teacher":"parent");setToken(t);try{const x=await call("listLinkedLearners",t);setLearners(x.items||[])}catch(e:any){setError(e.message)}}}),[]);
 async function login(e:any){e.preventDefault();setBusy(true);setError("");try{await signInWithEmailAndPassword(auth,email.trim(),password)}catch(e:any){setError(e?.message?.replace("Firebase: ","")||"Unable to sign in.")}finally{setBusy(false)}}
 async function link(){if(!code.trim())return;setBusy(true);setError("");try{await call("linkLearner",token,{code});const x=await call("listLinkedLearners",token);setLearners(x.items||[]);setCode("")}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function view(id:string){setBusy(true);setError("");try{setSelected(await call("getLinkedLearnerProgress",token,{learnerId:id}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!user)return <><header className="top"><div className="wrap"><div className="brand">SKILL SAGA</div><h1>Parent & Teacher Portal</h1><p>Support learning with a clear view of progress.</p></div></header><main className="wrap"><div className="card"><span className="kicker">🔐 Secure access</span><h2>Sign in</h2><p>Use your Skill Saga parent or teacher account.</p><form onSubmit={login} className="link-row" style={{display:"grid"}}><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className="btn primary" disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form>{error&&<div className="error" style={{marginTop:15}}>{error}</div>}</div></main></>;
 if(role!=="parent"&&role!=="teacher")return <><header className="top"><div className="wrap"><div className="brand">SKILL SAGA</div><h1>Access restricted</h1><p>This portal is available only to parent and teacher accounts.</p></div></header><main className="wrap"><div className="card"><p>Your signed-in account does not have the required role.</p><button className="btn primary" style={{marginTop:15}} onClick={()=>signOut(auth)}>Sign out</button></div></main></>;
 return <><header className="top"><div className="wrap"><div className="brand">SKILL SAGA</div><h1>{role==="teacher"?"Teacher":"Parent"} Portal 👋</h1><p>See learning progress from securely linked learner accounts.</p></div></header>
 <main className="wrap">
  <div className="card"><div className="card-head"><div><span className="kicker">Your account</span><h2>Learning dashboard</h2><p>{user.email||"Signed-in account"}</p></div><span className="role-pill">{role==="teacher"?"👩‍🏫 Teacher":"👨‍👩‍👧 Parent"}</span></div></div>
  {error&&<div className="error">{error}</div>}
  <div className="card"><span className="kicker">🔗 Add learner</span><h2>Link a learner</h2><p>Ask the learner to generate a secure 15-minute link code from their Skill Saga profile.</p><div className="link-row"><input value={code} maxLength={6} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))} placeholder="Enter 6-character code"/><button className="btn primary" disabled={busy||code.length<4} onClick={link}>{busy?"Linking…":"Link Learner"}</button></div><div className="notice"><span className="notice-icon">⏱️</span><p>The code expires after 15 minutes and becomes inactive after successful linking.</p></div></div>
  <div className="card"><span className="kicker">🌟 Your learners</span><h2>Linked learners</h2>{!learners.length?<div className="empty"><div style={{fontSize:38}}>🎒</div><h3>No learners linked yet</h3><p>Link a learner using the code from their profile to start viewing progress.</p></div>:<div className="learner-list">{learners.map(x=><div className="learner-card" key={x.id}><div style={{display:"flex",gap:12,alignItems:"center",minWidth:0}}><div className="avatar">🎓</div><div className="learner-info"><strong>{x.displayName||x.email||"Learner"}</strong><span>{x.email||"Linked learner"}</span></div></div><button className="btn primary" onClick={()=>view(x.learnerId)} disabled={busy}>View Progress</button></div>)}</div>}</div>
  {selected&&<div className="card"><div className="card-head"><div><span className="kicker">📈 Learner overview</span><h2>{selected.learner.displayName||selected.learner.email||"Learner"}</h2><p>Recent learning activity and performance</p></div><span className="role-pill">🌱 Growing</span></div><div className="stats"><div className="stat-card"><small>⭐ XP</small><div className="stat">{selected.stats.xp}</div></div><div className="stat-card"><small>🪙 Coins</small><div className="stat">{selected.stats.coins}</div></div><div className="stat-card"><small>🚀 Level</small><div className="stat">{selected.stats.level}</div></div><div className="stat-card"><small>🎯 Accuracy</small><div className="stat">{selected.stats.accuracy}%</div></div></div><h3>Subject performance</h3><div className="subject-grid">{(selected.subjectPerformance||[]).map((s:any)=><div className="stat-card" key={s.subject}><small>{s.subject}</small><div className="stat">{s.accuracy}%</div><span>{s.correct}/{s.total}</span></div>)}</div><h3>Recent activity</h3><div className="table-wrap"><table><thead><tr><th>Quiz</th><th>Score</th><th>Accuracy</th></tr></thead><tbody>{selected.attempts.map((a:any)=><tr key={a.id}><td>{a.quizId}</td><td>{a.correct}/{a.total}</td><td>{a.percentage}%</td></tr>)}</tbody></table></div></div>}
 </main></>;
}