"use client";
import{useEffect,useState}from"react";
import{firebaseAuth}from"../../lib/firebase";
type UserItem={uid:string;email:string;displayName:string;disabled:boolean;emailVerified:boolean;createdAt:string|null;lastSignInAt:string|null;role:string};
const roles=["learner","parent","teacher","school_admin","content_manager","moderator","support","finance","admin","super_admin"];
export default function UsersManager(){
 const[items,setItems]=useState<UserItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[diagnostics,setDiagnostics]=useState<any>(null);
 async function call(action:string,data:any={}){
  const u=firebaseAuth.currentUser;if(!u)throw new Error("You are not authenticated.");
  const token=await u.getIdToken();
  const r=await fetch("/api/users",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({action,data})});
  const p=await r.json();if(!r.ok)throw new Error(p.error?.message||"User request failed.");return p.data;
 }
 async function load(){setLoading(true);setError(null);try{const p=await call("listUsers");setItems(p.items??[]);setDiagnostics(p.authDiagnostics??null)}catch(e){setError(e instanceof Error?e.message:"Unable to load users.");}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function update(uid:string,data:any){setBusy(uid);setError(null);setMessage(null);try{await call("updateUser",{uid,...data});setMessage("User updated successfully.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update user.");}finally{setBusy(null)}}
 return <main className="academic-manager"><header className="academic-header"><div><span className="academic-eyebrow">USERS</span><h1>User Management</h1><p>Firebase Authentication users managed through the server.</p></div></header>{message&&<div className="academic-message success">{message}</div>}{error&&<div className="academic-message error">{error}</div>}<section className="academic-panel"><div className="academic-panel-header"><div><h2>Registered Users</h2><p>{items.length} users loaded. User deletion is intentionally not available; accounts can be disabled instead.</p></div></div>{diagnostics&&items.length===0&&<div className="academic-message error">No Firebase Authentication users were returned by the server. Project: {diagnostics.functionsProject||"—"} · Auth emulator: {diagnostics.firebaseAuthEmulatorHost||"not configured"} · Current UID: {diagnostics.requestedUid||"—"} · Auth directory count: {diagnostics.directoryCount??0}</div>}{loading?<div className="academic-empty">Loading users…</div>:<div className="academic-table-wrap"><table className="academic-table"><thead><tr><th>Email</th><th>Role</th><th>Status</th><th>Verified</th><th>Last Sign In</th><th>Actions</th></tr></thead><tbody>{items.map(user=><tr key={user.uid}><td><strong>{user.email||"No email"}</strong><small>{user.uid}</small></td><td><select value={user.role} disabled={busy===user.uid} onChange={e=>update(user.uid,{role:e.target.value})}>{roles.map(role=><option key={role} value={role}>{role}</option>)}</select></td><td><span className={`status-pill ${user.disabled?"":"active"}`}>{user.disabled?"Disabled":"Active"}</span></td><td>{user.emailVerified?"Verified":"Unverified"}</td><td>{user.lastSignInAt?new Date(user.lastSignInAt).toLocaleString():"Never"}</td><td><button className={user.disabled?"primary-button":"secondary-button"} disabled={busy===user.uid} onClick={()=>update(user.uid,{disabled:!user.disabled})}>{busy===user.uid?"Saving…":user.disabled?"Enable":"Disable"}</button></td></tr>)}</tbody></table></div>}</section></main>
}
