"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { learnerAuth } from "../../lib/firebase";

type Stats={xp:number;coins:number;level:number;streak:number;attempts:number;correct:number;answered:number;accuracy:number};
type Attempt={id:string;quizId:string;correct:number;total:number;percentage:number;xpEarned:number;coinsEarned:number};

async function call(action:string,token:string){const r=await fetch("/api/learner-quiz",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({action,data:{}})});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"Request failed.");return p?.data??p;}

export default function Profile(){
 const [stats,setStats]=useState<Stats|null>(null),[attempts,setAttempts]=useState<Attempt[]>([]),[error,setError]=useState("");
 useEffect(()=>onAuthStateChanged(learnerAuth,async user=>{if(!user)return;try{const token=await user.getIdToken();const [s,h]=await Promise.all([call("getLearnerStats",token),call("listLearnerAttempts",token)]);setStats(s.stats);setAttempts(h.items||[]);}catch(e:any){setError(e.message||"Unable to load profile.");}}),[]);
 return <div className="ss-shell"><header className="ss-top"><div className="ss-wrap"><div className="ss-brand">SKILL SAGA · PROFILE</div><h1>Profile</h1><p>Your learning identity, progress and shortcuts.</p></div></header><main className="ss-main">
 <div className="ss-card"><div style={{display:"flex",gap:16,alignItems:"center"}}><div style={{width:64,height:64,borderRadius:"50%",background:"#e8eef9",display:"grid",placeItems:"center",fontSize:28}}>👤</div><div><h2 style={{margin:0}}>{learnerAuth.currentUser?.email||"Learner"}</h2><p>Level {stats?.level??1} · {stats?.xp??0} XP · {stats?.streak??0} day streak</p></div></div></div>
 {error&&<div className="ss-card" style={{marginTop:14}}><p>{error}</p></div>}
 <section style={{marginTop:14}}><div className="ss-grid"><div className="ss-card"><span className="ss-eyebrow">XP</span><div className="ss-stat">{stats?.xp??0}</div><p>Total experience</p></div><div className="ss-card"><span className="ss-eyebrow">Coins</span><div className="ss-stat">{stats?.coins??0} 🪙</div><p>Available earned coins</p></div><div className="ss-card"><span className="ss-eyebrow">Accuracy</span><div className="ss-stat">{stats?.accuracy??0}%</div><p>Across answered questions</p></div><div className="ss-card"><span className="ss-eyebrow">Quizzes</span><div className="ss-stat">{stats?.attempts??0}</div><p>Completed attempts</p></div></div></section>
 <section style={{marginTop:20}}><div className="ss-card"><span className="ss-eyebrow">Quiz History</span><h2>Recent attempts</h2>{attempts.length===0?<p>No completed quizzes yet.</p>:attempts.slice(0,10).map(a=><div key={a.id} style={{padding:"12px 0",borderTop:"1px solid #e7ebf2",display:"flex",justifyContent:"space-between",gap:10}}><div><strong>Quiz {a.quizId.slice(0,8)}</strong><p>{a.correct}/{a.total} correct · +{a.xpEarned} XP · +{a.coinsEarned} coins</p></div><strong>{a.percentage}%</strong></div>)}</div></section>
 <section style={{marginTop:20}}><div className="ss-card"><span className="ss-eyebrow">Parent / Teacher Link</span><h2>Share your learning securely</h2><p>Generate a 15-minute link code for a parent or teacher. They can use it to view your progress.</p><button className="ss-btn" onClick={async()=>{const u=learnerAuth.currentUser;if(!u)return;const t=await u.getIdToken();const r=await fetch("/api/learner-quiz",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({action:"createLearnerLinkCode",data:{}})});const p=await r.json();alert(p?.data?.code||p?.error?.message||"Unable to generate code.");}}>Generate Link Code</button></div></section><div className="ss-actions"><Link href="/progress" className="ss-btn primary">View Detailed Progress</Link><Link href="/rewards" className="ss-btn">Rewards & Coins</Link><Link href="/play" className="ss-btn">Take a Quiz</Link><Link href="/" className="ss-btn">Home</Link></div>
 </main><Nav/></div>;
}
function Nav(){return <nav className="ss-nav"><div className="ss-nav-inner">{[["⌂","Home","/"],["📚","Learn","/learn"],["▶","Play","/play"],["🏆","Compete","/compete"],["👤","Profile","/profile"]].map(([i,l,h])=><Link key={l} className={l==="Profile"?"active":""} href={h}><span className="ss-icon">{i}</span>{l}</Link>)}</div></nav>}