"use client";
import{useEffect,useState}from"react";import{onAuthStateChanged,signInWithEmailAndPassword,signOut}from"firebase/auth";import{schoolAuth}from"./lib/firebase";import{schoolFunction}from"./lib/api";
const tabs=["dashboard","classes","students","teachers","tests","competitions","assignments","reports","analytics"];
export default function School(){const[d,setD]=useState<any>({}),[u,setU]=useState<any>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[tab,setTab]=useState("dashboard"),[members,setMembers]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]),[busy,setBusy]=useState(false);
useEffect(()=>onAuthStateChanged(schoolAuth,async x=>{setU(x);if(x)try{setD(await schoolFunction("getSchoolDashboard",{},await x.getIdToken()))}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard.")}}),[]);
async function load(x:string){if(!u)return;setError("");try{const t=await u.getIdToken();if(x==="members"){const r=await schoolFunction("listSchoolMembers",{},t);setMembers(r.items||[])}if(x==="assignments"){const r=await schoolFunction("listSchoolAssignments",{},t);setAssignments(r.items||[])}}catch(e){setError(e instanceof Error?e.message:"Unable to load data.")}}
async function open(x:string){setTab(x);if(["classes","students","teachers"].includes(x))await load("members");if(x==="assignments")await load("assignments")}
async function updateMember(m:any){if(!u)return;try{setBusy(true);await schoolFunction("updateSchoolMember",{id:m.id,data:{displayName:m.displayName,classId:m.classId,active:m.active}},await u.getIdToken());setMessage("Member updated.");await load("members")}catch(e){setError(e instanceof Error?e.message:"Unable to update member.")}finally{setBusy(false)}}
async function login(e:any){e.preventDefault();setError("");try{await signInWithEmailAndPassword(schoolAuth,email.trim(),password)}catch(e:any){setError(e?.message||"Sign in failed.")}}
if(!u)return <main className="school-login"><form onSubmit={login}><div className="brand">Skill Saga <span>School</span></div><h1>School Administrator</h1><p>Manage your school learning operations.</p><input type="email" required placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button>Sign In</button>{error&&<div className="error">{error}</div>}</form></main>;
const filtered=members.filter(m=>tab==="students"?m.role==="learner":tab==="teachers"?m.role==="teacher":true);
return <main className="school-shell"><header><div><div className="brand">Skill Saga <span>School</span></div><p>{d.school?.name||"School administration"} · Central school workspace</p></div><button onClick={()=>signOut(schoolAuth)}>Sign out</button></header><nav>{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>open(x)} key={x}>{x}</button>)}</nav>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}
{tab==="dashboard"&&<><div className="grid">{[[d.teachersCount,"Teachers"],[d.studentsCount,"Students"],[d.classesCount,"Classes"],[d.assignmentsCount,"Assignments"]].map(([n,l])=><article key={l}><b>{n??0}</b><span>{l}</span></article>)}</div><section className="panel"><h2>School Operations</h2><p>Manage your roster, assignments and school learning activity from one workspace.</p><div className="quick"><button onClick={()=>open("students")}>View Students</button><button onClick={()=>open("teachers")}>View Teachers</button><button onClick={()=>open("assignments")}>View Assignments</button></div></section></>}
{["classes","students","teachers"].includes(tab)&&<section className="panel"><h2>{tab[0].toUpperCase()+tab.slice(1)}</h2><p>{filtered.length} records in your school</p><div className="table">{filtered.map(m=><div className="member" key={m.id}><div><b>{m.displayName||"Unnamed"}</b><small>{m.email} · {m.role}</small></div><input value={m.classId} placeholder="Class ID" onChange={e=>setMembers(members.map(x=>x.id===m.id?{...x,classId:e.target.value}:x))}/><select value={m.active?"active":"inactive"} onChange={e=>setMembers(members.map(x=>x.id===m.id?{...x,active:e.target.value==="active"}:x))}><option value="active">Active</option><option value="inactive">Inactive</option></select><button disabled={busy} onClick={()=>updateMember(m)}>Save</button></div>)}</div></section>}
{tab==="assignments"&&<section className="panel"><h2>School Assignments</h2>{assignments.length===0?<p>No school-wide assignments yet.</p>:<div className="table">{assignments.map(a=><div className="member" key={a.id}><div><b>{a.title}</b><small>{a.resourceType} · Due {a.dueAtMs?new Date(Number(a.dueAtMs)).toLocaleString():"No due date"}</small></div><span>{a.active?"Active":"Inactive"}</span></div>)}</div>}</section>}
{["tests","competitions","reports","analytics"].includes(tab)&&<section className="panel"><h2>{tab[0].toUpperCase()+tab.slice(1)}</h2><p>This school module is authenticated and connected to the platform. Dedicated test, competition, reporting and analytics controls are the next integration layer; no fake data is displayed.</p>{tab==="analytics"&&<div className="grid"><article><b>{d.studentsCount??0}</b><span>Students</span></article><article><b>{d.teachersCount??0}</b><span>Teachers</span></article><article><b>{d.assignmentsCount??0}</b><span>Assignments</span></article></div>}</section>}
</main>}
