"use client";
import{useEffect,useState}from"react";
import{firebaseAuth}from"../../lib/firebase";
const labels=[["questions","Questions"],["quizzes","Quizzes"],["competitions","Competitions"],["rewards","Rewards"],["notificationTemplates","Notification Templates"],["communityPosts","Community Posts"],["automationRules","Automation Rules"]] as const;
type Diagnostic={count:number;sampleIds:string[]};
export default function AnalyticsManager(){
 const[data,setData]=useState<Record<string,number>|null>(null),[diagnostics,setDiagnostics]=useState<Record<string,Diagnostic>|null>(null),[environment,setEnvironment]=useState<Record<string,string|null>|null>(null),[error,setError]=useState<string|null>(null);
 useEffect(()=>{(async()=>{try{const u=firebaseAuth.currentUser;if(!u)throw new Error("You are not authenticated.");const t=await u.getIdToken();const r=await fetch("/api/analytics",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({})});const p=await r.json()as any;if(!r.ok)throw new Error(p.error?.message||"Unable to load analytics.");setData(p.data?.counts??{});setDiagnostics(p.data?.diagnostics??null);setEnvironment(p.data?.environment??null)}catch(e){setError(e instanceof Error?e.message:"Unable to load analytics.")}})()},[]);
 return <main className="academic-manager"><header className="academic-header"><div><span className="academic-eyebrow">ANALYTICS</span><h1>Platform Analytics</h1><p>Live counts from the central development database.</p></div></header><section className="cards">{labels.map(([key,label])=><article key={key}><span>{label}</span><strong>{data?data[key]??0:"—"}</strong><small>Database records</small></article>)}</section>{error&&<div className="academic-message error">{error}</div>}<section className="academic-panel"><h2>Analytics Database Diagnostic</h2><p>Temporary diagnostic view: this confirms which Firestore connection Analytics is reading and shows sample document IDs.</p>{environment&&<div style={{marginBottom:16}}><strong>Project:</strong> {environment.projectId||"—"} &nbsp; <strong>Firestore emulator:</strong> {environment.firestoreEmulatorHost||"not set"}</div>}{diagnostics&&<div className="academic-table-wrap"><table className="academic-table"><thead><tr><th>Collection</th><th>Server count</th><th>Sample document IDs</th></tr></thead><tbody>{labels.map(([key,label])=><tr key={key}><td>{label}</td><td>{diagnostics[key]?.count??0}</td><td>{diagnostics[key]?.sampleIds?.join(", ")||"—"}</td></tr>)}</tbody></table></div>}</section></main>
}