"use client";
import{useEffect,useState}from"react";import{onAuthStateChanged,signInWithEmailAndPassword,signOut}from"firebase/auth";import{parentAuth}from"./lib/firebase";import{parentFunction}from"./lib/api";
export default function Parent(){const[u,setU]=useState<any>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[tab,setTab]=useState("overview"),[children,setChildren]=useState<any[]>([]),[selected,setSelected]=useState(""),[progress,setProgress]=useState<any>(null),[code,setCode]=useState(""),[busy,setBusy]=useState(false);
useEffect(()=>onAuthStateChanged(parentAuth,async x=>{setU(x);if(x)loadChildren(x)}),[]);
async function loadChildren(x:any=u){if(!x)return;try{const r=await parentFunction("listLinkedLearners",{},await x.getIdToken());setChildren(r.items||[]);if(!selected&&r.items?.[0]?.learnerId)setSelected(r.items[0].learnerId)}catch(e){setError(e instanceof Error?e.message:"Unable to load children.")}}
useEffect(()=>{if(u&&selected)loadProgress()},[selected,u]);
async function loadProgress(){try{setProgress(await parentFunction("getLinkedLearnerProgress",{learnerId:selected},await u.getIdToken()))}catch(e){setError(e instanceof Error?e.message:"Unable to load child progress.")}}
async function login(e:any){e.preventDefault();setError("");setBusy(true);try{await signInWithEmailAndPassword(parentAuth,email.trim(),password)}catch(e:any){setError(e?.message||"Sign in failed.")}finally{setBusy(false)}}
async function link(){if(!code.trim())return;try{setBusy(true);await parentFunction("linkLearner",{code:code.trim()},await u.getIdToken());setCode("");await loadChildren()}catch(e){setError(e instanceof Error?e.message:"Unable to link learner.")}finally{setBusy(false)}}
if(!u)return <main className="login"><section className="card"><div className="brand">Skill Saga <span>Parent</span></div><h1>Parent Sign In</h1><p>Stay connected with your child's learning journey.</p><input className="input" type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="input" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary" disabled={busy} onClick={login}>{busy?"Signing in…":"Sign In"}</button>{error&&<div>{error}</div>}</section></main>;
const s=progress?.stats||{};return <main className="parent-shell"><header><div><div className="brand">Skill Saga <span>Parent</span></div><p>Parent Dashboard · Track learning, progress and activity.</p></div><button onClick={()=>signOut(parentAuth)}>Sign out</button></header><div className="nav">{["overview","performance","activity","children"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{error&&<div className="card">{error}</div>}{children.length===0&&<section className="card"><h2>Connect your child</h2><p>Ask your child to generate a Parent Link Code from their Skill Saga profile.</p><input className="input" placeholder="6-character link code" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button className="primary" onClick={link} disabled={busy}>Link Child</button></section>}{children.length>0&&<><section className="card"><h2>{progress?.learner?.displayName||"Your Child"}</h2><select className="input" value={selected} onChange={e=>setSelected(e.target.value)}>{children.map(c=><option key={c.learnerId} value={c.learnerId}>{c.learnerId}</option>)}</select></section>{tab==="overview"&&<><div className="stats"><div className="card"><b>{s.level??1}</b><span>Level</span></div><div className="card"><b>{s.xp??0}</b><span>XP</span></div><div className="card"><b>{s.coins??0}</b><span>Coins</span></div><div className="card"><b>{s.accuracy??0}%</b><span>Accuracy</span></div></div><div className="grid"><section className="card"><h2>Subject Performance</h2>{(progress?.subjectPerformance||[]).map((x:any)=><div className="subject" key={x.subject}><strong>{x.subject}</strong><small>{x.accuracy}% accuracy · {x.correct}/{x.total} correct</small></div>)}</section><section className="card"><h2>Recent Activity</h2>{(progress?.attempts||[]).slice(0,8).map((x:any)=><div className="attempt" key={x.id}><strong>{x.subject}</strong><small>{x.percentage}% · {x.correct}/{x.total}</small></div>)}</section></div></>}
{tab==="performance"&&<section className="card"><h2>Performance by Subject</h2>{(progress?.subjectPerformance||[]).map((x:any)=><div className="subject" key={x.subject}><strong>{x.subject}</strong><div>{x.accuracy}% accuracy</div><small>{x.correct} correct out of {x.total}</small></div>)}</section>}
{tab==="activity"&&<section className="card"><h2>Quiz History</h2>{(progress?.attempts||[]).map((x:any)=><div className="attempt" key={x.id}><strong>{x.subject}</strong><small>{x.percentage}% · {x.correct}/{x.total}</small></div>)}</section>}
{tab==="children"&&<section className="card"><h2>Linked Children</h2>{children.map(c=><div className="attempt" key={c.id}><strong>{c.learnerId}</strong><small>{c.status}</small></div>)}</section>}</>}</main>}